# Generated by Django 2.2 on 2020-03-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='new_users.UserProfile'),
        ),
    ]
