# Generated by Django 2.2 on 2020-02-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('store_location', models.CharField(max_length=30)),
                ('store_address', models.CharField(max_length=60)),
                ('store_latitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('store_longitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('store_city', models.CharField(max_length=30)),
                ('store_state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_price', models.FloatField()),
                ('product_discount_price', models.FloatField()),
                ('product_description', models.TextField(max_length=801)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Store')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Store'),
        ),
    ]
