# Generated by Django 2.2 on 2020-03-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
