# Generated by Django 2.2 on 2020-03-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_users', '0004_auto_20200311_1123'),
        ('trialapp', '0002_auto_20200305_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='follower',
            field=models.ManyToManyField(related_name='followers', through='trialapp.Followership', to='new_users.UserProfile'),
        ),
    ]
