# Generated by Django 2.2 on 2020-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_auto_20200311_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', through='trialapp.Followership', to='new_users.UserProfile'),
        ),
    ]
