# Generated by Django 2.2 on 2020-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_store_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
