# Generated by Django 2.2 on 2020-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_auto_20200311_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unfollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', through='trialapp.Followership', to='new_users.UserProfile'),
        ),
    ]
