# Generated by Django 2.2 on 2020-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
