# Generated by Django 2.2 on 2020-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0006_auto_20200312_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followership',
            name='reason',
            field=models.CharField(blank=True, choices=[('1', 'not intrested'), ('2', 'high price'), ('3', 'not liked'), ('4', 'other')], max_length=1, null=True),
        ),
    ]
